name: Build macOS M1 mihomo

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write


jobs:

  build-macos-arm64:

    runs-on: macos-14


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Clone mihomo
        run: |
          git clone https://cnb.cool/cnmeeia/mihomo mihomo
          cd mihomo
          git checkout "${GITHUB_REF_NAME}"


      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable


      - name: Rust target
        run: |
          rustup target add aarch64-apple-darwin


      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: mihomo/package-lock.json


      - name: Install dependencies
        working-directory: mihomo
        run: npm ci

      - name: Install tools
        run: |
          brew install create-dmg


      - name: Build Helper Tool
        run: |
          bash scripts/build-helper.sh src-tauri/resources

          ls -lh \
          src-tauri/resources/mihomo-helper \
          src-tauri/resources/mihomo-helperctl

          rm -f \
          src-tauri/resources/mihomo-helper \
          src-tauri/resources/mihomo-helperctl


      - name: Fetch mihomo kernel
        run: |
          bash scripts/fetch-kernel.sh


      - name: Build Tauri
        run: |
          npm run app:build


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.tar.gz